### ISSUE TITLE
Feature: Support AWS Batch

### ISSUE THREAD

**Issue by chadbrewbaker** [awslabs/aws-lambda-container-image-converter#13]
It would be amazing to be able to deploy the same code to AWS Lambda and AWS Batch with an initial queue size of zero for longer running jobs.  It would compile to a lambda trigger that kicked off the batch job.

Happy to write a PR myself, but I need a little direction on the best workflow. Would it be as easy as calling the existing https://github.com/aws/aws-parallelcluster scripts?

**Comment by clareliguori** [comment]
Hey, I'm not super familiar with Batch, but that sounds like a cool idea.  However, I think it makes more sense to write it as a standalone tool in its own repo, which maybe uses img2lambda in one of the steps to convert a Docker image to Lambda layers.
