### ISSUE TITLE
Provide option for daemon on Windows 7

### ISSUE THREAD

**Issue by aibot221** [awslabs/aws-lambda-container-image-converter#26]
### Windows 7 Issue

If you could provide a flag/option on the build to point the daemon at a different port, this would resolve the issue.

When DockerToolbox installs, it points the daemon to 2376 on Windows 7. Windows 10 (Docker desktop) provides an option to bind to port 2375.

### Expected output
Lambda layer deployed to AWS

### Actual output
`2019/06/21 16:36:55 Parsing the image docker-daemon:af:latest
2019/06/21 16:36:55 Error loading image from docker engine: error during connect: Get https://%2F%2F.%2Fpipe%2Fdocker_engine/v1.22/images/get?names=af%3Alatest: dial tcp: lookup //./pipe/docker_engine: no such host`

**Comment by clareliguori** [comment]
It will already respect the value of DOCKER_HOST environment variable being set to "tcp://127.0.0.1:2375" or "tcp://localhost:2375".  Can you test that?
