### ISSUE TITLE
Using assumed role profile puts layer in wrong account

### ISSUE THREAD

**Issue by pagameba** [awslabs/aws-lambda-container-image-converter#46]
Hi I'm using an assumed role profile as follows:

`img2lambda -i built-image:latest --profile otheraccount`

and it is uploading the layer to the account for my `default` profile rather than the `otheraccount` profile.  Seems like this should be using the account id for `otheraccount` based on the docs so I'm thinking its a configuration issue but all other aws cli stuff works so I'm a bit stuck.

My aws configs look like this:

~/.aws/config

```
[default]
region = us-east-1
output = json

[profile otheraccount]
role_arn = arn:aws:iam::<other-account-id>:role/AccountAccessRole
source_profile = default
```

~/.aws/credentials

```
[default]
aws_access_key_id=<key>
aws_secret_access_key=<secret>

[otheraccount]
role_arn = arn:aws:iam::<other-account-id>:role/AccountAccessRole
source_profile = default
region = us-east-1
```

**Comment by clareliguori** [comment]
I think I understand the root cause.  Can you try doing:
```AWS_SDK_LOAD_CONFIG=true img2lambda -i built-image:latest --profile otheraccount```

**Comment by pagameba** [comment]
Gave it a shot, sadly it did not use the correct account id again.

**Comment by clareliguori** [comment]
Try this release:
https://github.com/awslabs/aws-lambda-container-image-converter/releases/tag/1.1.0

This change *should* fix this: 37ac6e8a6f4109552324eb3a5a19b36e4d62d58e
According to the Go SDK docs anyway: https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Shared_Config_Fields

```
If the AWS_SDK_LOAD_CONFIG environment variable is set, or SharedConfigEnable option is used to create the Session the full shared config values will be loaded. This includes credentials, region, and support for assume role.
```

**Comment by pagameba** [comment]
Brilliant!  It works perfectly, thank you.  Is there any downside to me having that in my default environment (e.g. will it screw up non-assumed-role things)?

**Comment by clareliguori** [comment]
You mean having role_arn in the default profile?  I think `role_arn` requires either a `source_profile` or a `credential_source`.  But if you have a credential source (like EC2 instance metadata creds), it seems fine to put role_arn in the default profile.
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles
