### ISSUE TITLE
Layer creation error

### ISSUE THREAD

**Issue by AntonOellerer** [awslabs/aws-lambda-container-image-converter#48]
Hey, I have a container where I build `vips` and then copy it to the /opt directory with
```
RUN cp -r /lib/*.so.* /opt/lib/
RUN cp -r /lib64/*.so.* /opt/lib/
```
Now when trying to run the script, it fails at the relevant image with the error
```
2019/11/28 13:25:16 could not read layer with tar nor tar.gz: walking libvips-cpp.so.42 in layer tar: lib/libvips-cpp.so.42: readlink: readlink lib/libvips-cpp.so.42: no such file or directory, opening next file in layer tar: archive/tar:
 invalid tar header                        
```
Do you know what the problem here is?

**Comment by clareliguori** [comment]
Based on the error message, it sounds like there are some symbolic links that are not copied correctly into /opt.  Try using `cp -a` instead of `cp -r`

**Comment by AntonOellerer** [comment]
I am copying with `cp -r -L` now and now it works, thank you!
