### ISSUE TITLE
Feature: Support Lambda compatible runtimes other than 'provided'

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-lambda-container-image-converter#5]
Publish step always uses 'provided' runtime for the new layers.  Support other runtimes -- for example, support images that are based off of lambci/lambda:nodejs8.10

**Comment by asahasrabuddhe** [comment]
How do we determine what are the compatible runtimes for the current layer being pushed? Through commandline parameters or the image tag to relate it to one of the already supported runtimes?

**Comment by clareliguori** [comment]
I think a command-line parameter that takes a list.  For example, a Docker image with an ffmpeg binary can be used as a Lambda layer with any runtime ([example here](https://serverless.pub/lambda-utility-layers/)), but it doesn't seem possible to tell that just from looking at the Docker image.
