### ISSUE TITLE
Feature: Extract function deployment packages

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-lambda-container-image-converter#6]
Docker build is useful for building function code too!  Support a mode that extracts files from /var/task/src (for function deployment package) instead of /opt (used for layers).

**Comment by asahasrabuddhe** [comment]
This certainly seems interesting. What would you think should be a right way to go around this? We could probably have a cli flag that would allow:

1. only runtime
2. only functional code
3. both

Please let me know your thoughts. I'd love to contribute :)

**Comment by clareliguori** [comment]
Yep, that's exactly what I was thinking, something like --filter or --mode

**Comment by asahasrabuddhe** [comment]
I am working on this now and was wondering do we want a zip of the function code as the output or should we just deploy (create/update) the function to lambda?

**Comment by clareliguori** [comment]
This is an issue I'd like leave open for a bit to wait and get some more feedback on what behavior people need.  There's a lot of API options to duplicate for creating a function, so I'm hesitant to go that route immediately.  Plus, I'm interested to hear people's thoughts on how this tool might integrate with other ways of provisioning functions like CloudFormation, SAM, Terraform, etc

**Comment by asahasrabuddhe** [comment]
@clareliguori any updates on this?

**Comment by clareliguori** [comment]
@asahasrabuddhe I think this behavior would make the most sense: img2lambda always tries to extract a function deployment package from /var/task/src, but never publishes it.  It only writes it out to output-directory/function.zip.  The user is then responsible for deploying the deployment package to their Lambda function.

**Comment by asahasrabuddhe** [comment]
@clareliguori this makes sense. Let me put together 2 and 2 together and get back to you in a few days with something

**Comment by clareliguori** [comment]
Fixed in a3c8d946fc7d963104f35ba3e8e6a0da69880cc7
