### ISSUE TITLE
help with installation

### ISSUE THREAD

**Issue by huemansdesign** [awslabs/aws-lambda-container-image-converter#69]
Hi all, thanks for this, very cool. Apologies if this is too newbie of a question but I'm trying to utilize the darwin binaries on my mac, preferring not to build from source. I downloaded and attempted to run via targeting from bash but darwin-amd64-img2lamba is not recognized

sensei:~ *******$ sudo  ~/Downloads/darwin-amd64-img2lambda  --version
Password:
sudo: /Users/elcapitano/Downloads/darwin-amd64-img2lambda: command not found
sensei:~ *******$ 

Should I be able to use the darwin-amd64-img2lambda  on  mac out of the box, anything I'm missing on how to utilize the binary?

Thanks!

**Comment by PettitWesley** [comment]
Hey @huemansdesign the following worked for me:

```
$ /Users/wppttt/Downloads/darwin-amd64-img2lambda
-bash: /Users/wppttt/Downloads/darwin-amd64-img2lambda: Permission denied
amazon-kinesis-firehose-for-fluent-bit (1.2.0) $ chmod +x /Users/wppttt/Downloads/darwin-amd64-img2lambda
amazon-kinesis-firehose-for-fluent-bit (1.2.0) $ /Users/wppttt/Downloads/darwin-amd64-img2lambda
ERROR: Image name is required
... help text for the command ...
```

Obviously it's probably easier to put it in your $PATH instead of using the full path to executable.

**Comment by huemansdesign** [comment]
Got it sorry, was advised to run chmod +x  on the binary. Works!
