### ISSUE TITLE
fail to run in wsl

### ISSUE THREAD

**Issue by riponbanik** [awslabs/aws-lambda-container-image-converter#7]
While running the tool under wsl (Windows Subsystem for Linux), it shows the following error -

Error loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I can run and build the docker images using the docker command.

Will you be able to change the local socket dependency ? docker info result is below

Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 11
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155df88701
ID: 43BH:53TT:6MAF:XAIP:MHPN:KSQU:42NS:YEPJ:HWOL:SLZ2:MHJU:3FMH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2019-01-24T06:18:10.6113087Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by clareliguori** [comment]
Is your docker client using a TCP connection or pipe to connect to Docker? What is the value of DOCKER_HOST environment variable?

**Comment by clareliguori** [comment]
Can you try this release?
https://github.com/awslabs/aws-lambda-container-image-converter/releases/tag/0.0.2

**Comment by riponbanik** [comment]
@clareliguori  Thanks for the quick response. That is why you are the best. Shows the follow error now. 

2019/01/25 09:31:24 Parsing the docker image docker-daemon:lambda-php:latest
2019/01/25 09:31:24 Error loading image from docker engine: error during connect: Get https://127.0.0.1:2375/v1.22/images/get?names=lambda-php%3Alatest: http: server gave HTTP response to HTTPS client

Also you can change like the following since for some config I know 0.0.0.0 also works -

dockerHost := os.Getenv("DOCKER_HOST")
	if dockerHost == "tcp://localhost:2375" || dockerHost == "tcp://127.0.0.1:2375" ||  dockerHost == "tcp://0.0.0.1:2375" {
		sys.DockerDaemonHost = dockerHost
	}

**Comment by clareliguori** [comment]
Ok try this release:
https://github.com/awslabs/aws-lambda-container-image-converter/releases/tag/0.0.3

@allisaurus graciously tested it on her Windows machine for me :smile:

Related commit: https://github.com/awslabs/aws-lambda-container-image-converter/commit/90056a8f4e9a1a024da897fa2d8f84b0217e6fce

**Comment by riponbanik** [comment]
@clareliguori It works now!!!. Although it created 2 layers. Thanks heaps.

2019/01/25 12:33:21 Parsing the docker image docker-daemon:lambda-php:latest
2019/01/25 12:33:45 Image docker-daemon:lambda-php:latest has 5 layers
2019/01/25 12:33:47 Did not create a Lambda layer file from image layer sha256:3689366b03b394fe16903c2de2b26d0b2b651e049fce4de5eb365892b031d8d9 (no relevant files found)
2019/01/25 12:33:47 Did not create a Lambda layer file from image layer sha256:e561f3672c5fad29d71f2f69d48085e17cae144940d524e08332c54f4f4f7b81 (no relevant files found)
2019/01/25 12:33:48 Created Lambda layer file output/layer-1.zip from image layer sha256:36e9afe509189ebc5ad9e1ea763f1418b8d128506ac25e8902fbdcd06d98d498
2019/01/25 12:33:48 Created Lambda layer file output/layer-2.zip from image layer sha256:a0f7990bff9dfb7c2b81a9f45e0077e888691bb93ebbc37d67ff17e091ca9500
2019/01/25 12:33:48 Did not create a Lambda layer file from image layer sha256:f1e623da161313733665793734b85c46d40bcab533899e608507c41285a5c55d (no relevant files found)
2019/01/25 12:33:48 Created 2 Lambda layer files for image docker-daemon:lambda-php:latest
