### ISSUE TITLE
Enhancement: Use a spec-compliant PHP Runtime

### ISSUE THREAD

**Issue by asahasrabuddhe** [awslabs/aws-lambda-container-image-converter#8]
Hello,

Kudos for this excellent project. I have noticed that the example PHP Runtime that you are currently using for the example is not spec-compliant. It only implements two of the four interface methods. InitializationError and InvocationError methods are not implemented. Also, there is no Context object passed to the execution function.

Also, as per the AWS docs, the format for functions is filename.methodname which is also not followed in the used example.

I have implemented a custom PHP Runtime myself to take care of these issues and to be full spec compliant. I'd be issuing a PR for your example to use my runtime instead of the example one used. 

Please share your thoughts.

Regards,
Ajitem

**Comment by clareliguori** [comment]
Closing, a production PHP runtime isn't core to this project, and best served in a different repository
